# This file is part of compact-zed.
# Copyright (C) 2025 Midnight Foundation
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

id = "compact"
name = "Compact"
version = "1.0.0"
schema_version = 1
authors = ["Midnight Foundation <contact@midnight.network>"]
description = "Compact language support for Zed"
repository = "https://github.com/midnightntwrk/compact-zed"

[grammars.compact]
repository = "https://github.com/midnightntwrk/compact-tree-sitter"
rev = "409f9206ab3ca3cb53f8f3f4127012a8eb4ae36e"

[language_servers.compact]
language = "Compact"
name = "Compact LSP"
